service: image-uploader
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  iam:
    role:
      statements:
        - Effect: "Allow"
          Resource: "*"
          Action:
            - 's3:*'
            - lambda:InvokeFunction
            - lambda:InvokeAsync

# variables
some:
  s3:
    bucket: carrentalappleaf3demoproject

# files
files:
  generateUrl: handlers/generateUrl.handler
  imageUploader: handlers/imageUploader.handler

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: ${self:some.s3.bucket}
        CorsConfiguration:
          CorsRules:
            - AllowedHeaders:
                - '*'
              AllowedMethods:
                - PUT
                - GET
                - DELETE
                - POST
              AllowedOrigins:
                - '*'
    BucketPolicy:
      Type: AWS::S3::BucketPolicy
      Properties:
        Bucket: !Ref S3Bucket
        PolicyDocument:
          Statement:
            - Action:
                - s3:ListBucket
                - s3:GetObject
                - s3:PutObject
                - s3:DeleteObject
              Resource:
                - arn:aws:s3:::${self:some.s3.bucket}/*
                - arn:aws:s3:::${self:some.s3.bucket}
              Effect: Allow
              Principal: '*'

functions:
  generate:
    handler: ${self:files.generateUrl}
    events:
      - http:
          path: generate
          method: post
          cors: true
  imageUploader:
    handler: ${self:files.imageUploader}
